12-23 21:57:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS QUESTIONNAIRES.SCORE (IDUTILISATEURET INT NOT NULL , IDQCM INT NOT NULL , IDQUESTION INT NOT NULL , GOODANSWER TINYINT(1)) ,[*] PRIMARY KEY (IDUTILISATEURET , IDQCM , IDQUESTION); "; SQL statement:
CREATE TABLE IF NOT EXISTS Questionnaires.Score (idUtilisateurEt int not null , idQcm int not null , idQuestion int not null , goodAnswer tinyint(1)) , PRIMARY KEY (idUtilisateurEt , idQcm , idQuestion); [42000-174]
12-23 22:24:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:980)
	at org.h2.jdbc.JdbcStatement.checkClosedForWrite(JdbcStatement.java:965)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:120)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:113)
	at dao.data.CreateDataBase.insertingBd(CreateDataBase.java:51)
	at Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-23 22:25:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:980)
	at org.h2.jdbc.JdbcStatement.checkClosedForWrite(JdbcStatement.java:965)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:120)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:113)
	at dao.data.CreateDataBase.insertingBd(CreateDataBase.java:51)
	at Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-23 22:25:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:980)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:954)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:69)
	at dao.data.CreateDataBase.insertingBd(CreateDataBase.java:51)
	at Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-23 22:27:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:980)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:954)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:69)
	at dao.data.CreateDataBase.insertingBd(CreateDataBase.java:52)
	at Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-23 22:28:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:980)
	at org.h2.jdbc.JdbcStatement.checkClosedForWrite(JdbcStatement.java:965)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:120)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:113)
	at dao.data.CreateDataBase.insertingBd(CreateDataBase.java:52)
	at Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-23 22:29:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:189)
	at dao.data.CreateDataBase.insertingBd(CreateDataBase.java:49)
	at Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-23 22:30:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:189)
	at dao.data.CreateDataBase.insertingBd(CreateDataBase.java:49)
	at Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-23 23:38:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO QUESTIONNAIRES.FORMATION ('idFormation'[*], 'intituleFormation') VALUES (NULL, 'LICENCE 1') , ('NULL','LICENCE 2') , ('NULL','LICENCE 3') , ('NULL' , 'MASTER 1') , ('NULL' , 'MASTER 2'); "; expected "identifier"; SQL statement:
INSERT INTO Questionnaires.Formation ('idFormation', 'intituleFormation') VALUES (NULL, 'LICENCE 1') , ('NULL','LICENCE 2') , ('NULL','LICENCE 3') , ('NULL' , 'MASTER 1') , ('NULL' , 'MASTER 2'); [42001-174]
12-23 23:39:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO QUESTIONNAIRES.FORMATION ('idFormation'[*], 'intituleFormation') VALUES (NULL, 'LICENCE 1') , (NULL,'LICENCE 2') , (NULL,'LICENCE 3') , (NULL , 'MASTER 1') , (NULL , 'MASTER 2'); "; expected "identifier"; SQL statement:
INSERT INTO Questionnaires.Formation ('idFormation', 'intituleFormation') VALUES (NULL, 'LICENCE 1') , (NULL,'LICENCE 2') , (NULL,'LICENCE 3') , (NULL , 'MASTER 1') , (NULL , 'MASTER 2'); [42001-174]
12-23 23:39:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO QUESTIONNAIRES.FORMATION ('idFormation'[*], 'intituleFormation') VALUES ('NULL', 'LICENCE 1') , ('NULL','LICENCE 2') , ('NULL','LICENCE 3') , ('NULL' , 'MASTER 1') , ('NULL' , 'MASTER 2'); "; expected "identifier"; SQL statement:
INSERT INTO Questionnaires.Formation ('idFormation', 'intituleFormation') VALUES ('NULL', 'LICENCE 1') , ('NULL','LICENCE 2') , ('NULL','LICENCE 3') , ('NULL' , 'MASTER 1') , ('NULL' , 'MASTER 2'); [42001-174]
12-23 23:40:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO QUESTIONNAIRES.FORMATION ('idFormation'[*], 'intituleFormation') VALUES ('NULL', 'LICENCE 1'); "; expected "identifier"; SQL statement:
INSERT INTO Questionnaires.Formation ('idFormation', 'intituleFormation') VALUES ('NULL', 'LICENCE 1'); [42001-174]
12-23 23:40:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO QUESTIONNAIRES.FORMATION ('idFormation'[*], 'intituleFormation') VALUES (NULL, 'LICENCE 1'); "; expected "identifier"; SQL statement:
INSERT INTO Questionnaires.Formation ('idFormation', 'intituleFormation') VALUES (NULL, 'LICENCE 1'); [42001-174]
12-23 23:41:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO QUESTIONNAIRES.FORMATION ('intituleFormation'[*]) VALUES ('LICENCE 1'); "; expected "identifier"; SQL statement:
INSERT INTO Questionnaires.Formation ('intituleFormation') VALUES ('LICENCE 1'); [42001-174]
12-23 23:52:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO QUESTIONNAIRES.FORMATION ('intituleFormation'[*]) VALUES (?); "; expected "identifier"; SQL statement:
INSERT INTO Questionnaires.Formation ('intituleFormation') VALUES (?); [42001-174]
12-23 23:52:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO QUESTIONNAIRES.FORMATION ('intituleFormation'[*]) VALUES (?); "; expected "identifier"; SQL statement:
INSERT INTO Questionnaires.Formation ('intituleFormation') VALUES (?); [42001-174]
12-24 00:34:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "UTILISATEUR" not found; SQL statement:
SELECT * FROM UTILISATEUR WHERE nom = ? AND motDePasse = ?  [42102-174]
12-24 00:36:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Parameter "#4" is not set; SQL statement:
INSERT INTO QUESTIONNAIRES.UTILISATEUR (nomUtilisateur , prenomUtilisateur , motDePasse , idFormation) values (? , ? , ? , ?) ; [90012-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.Parameter.checkSet(Parameter.java:80)
	at org.h2.command.Prepared.checkParameters(Prepared.java:163)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at dao.UserDAO.addUser(UserDAO.java:94)
	at Main.main(Main.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-24 00:36:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "UTILISATEUR" not found; SQL statement:
SELECT * FROM UTILISATEUR WHERE nom = ? AND motDePasse = ?  [42102-174]
12-24 00:37:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "UTILISATEUR" not found; SQL statement:
SELECT * FROM UTILISATEUR WHERE nom = ? AND motDePasse = ?  [42102-174]
12-24 00:37:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'MASTER 1' (UTILISATEUR: IDFORMATION INT NOT NULL)"; SQL statement:
INSERT INTO QUESTIONNAIRES.UTILISATEUR (nomUtilisateur , prenomUtilisateur , motDePasse , idFormation) values (? , ? , ? , ?) -- (?1, ?2, ?3, ?4) [22018-174]
12-24 00:37:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "UTILISATEUR" not found; SQL statement:
SELECT * FROM UTILISATEUR WHERE nom = ? AND motDePasse = ?  [42102-174]
12-24 00:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "UTILISATEUR" not found; SQL statement:
SELECT * FROM UTILISATEUR WHERE nom = ? AND motDePasse = ?  [42102-174]
12-24 00:39:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "NOM" not found; SQL statement:
SELECT * FROM QUESTIONNAIRES.UTILISATEUR WHERE nom = ? AND motDePasse = ?  [42122-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Comparison.optimize(Comparison.java:177)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:131)
	at org.h2.command.dml.Select.prepare(Select.java:813)
	at org.h2.command.Parser.prepareCommand(Parser.java:231)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at dao.UserDAO.getUserByInfo(UserDAO.java:59)
	at Main.main(Main.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-26 12:34:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:265)
	at dao.UserDAO.getUserByInfo(UserDAO.java:70)
	at Main.main(Main.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-27 01:26:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:265)
	at dao.UserDAO.getMax(UserDAO.java:176)
	at Main.main(Main.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-27 01:29:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:265)
	at dao.UserDAO.getMax(UserDAO.java:177)
	at Main.main(Main.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-27 01:35:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:265)
	at dao.UserDAO.getMax(UserDAO.java:179)
	at Main.main(Main.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-28 12:11:19 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Table "QUESTION" not found; SQL statement:
SELECT * FROM Questionnaires.QCM natural join Question where idThematique = ? [42102-174]
12-28 12:38:56 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Column "IDQCM" not found; SQL statement:
SELECT * FROM Questionnaires.Choix where idQuestion = ? and idQcm = 3 [42122-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.expression.Comparison.optimize(Comparison.java:177)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:132)
	at org.h2.command.dml.Select.prepare(Select.java:813)
	at org.h2.command.Parser.prepareCommand(Parser.java:231)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at dao.QuestionDAO.getQuestionsByThematique(QuestionDAO.java:172)
	at Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-28 12:41:51 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Table "CHOIX" not found; SQL statement:
SELECT * FROM CHOIX [42102-174]
12-28 14:40:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:265)
	at dao.UserDAO.getAllUsers(UserDAO.java:112)
	at Main.main(Main.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
12-28 21:06:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1410)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:265)
	at dao.ThematiqueDAO.getAllThematiques(ThematiqueDAO.java:68)
	at Main.main(Main.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
01-05 23:32:08 database: close
org.h2.message.DbException: IO Exception: "java.io.EOFException"; "/Users/amineboufatah/IdeaProjects/projetL/src/db/ProjectLDataBase.h2.db" [90031-174]
	at org.h2.message.DbException.get(DbException.java:161)
	at org.h2.message.DbException.convertIOException(DbException.java:318)
	at org.h2.store.FileStore.readFully(FileStore.java:268)
	at org.h2.store.PageStore.readPage(PageStore.java:1291)
	at org.h2.store.PageStore.getPage(PageStore.java:738)
	at org.h2.store.PageStreamTrunk$Iterator.next(PageStreamTrunk.java:250)
	at org.h2.store.PageLog.free(PageLog.java:209)
	at org.h2.store.PageStore.compact(PageStore.java:491)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1241)
	at org.h2.engine.Database.close(Database.java:1191)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:64)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.EOFException"; "/Users/amineboufatah/IdeaProjects/projetL/src/db/ProjectLDataBase.h2.db" [90031-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 11 more
Caused by: java.io.EOFException
	at org.h2.store.fs.FileUtils.readFully(FileUtils.java:343)
	at org.h2.store.FileStore.readFully(FileStore.java:266)
	... 8 more
